name: Master
on:
  push:
    branches:
      - master

env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  USER_PATH: "/home/www"
  NODE_VERSION: 20
  DOMAIN: "app.parkangel.ru"
  REPO_URL: "git@github.com:MOSTEPP/app.parkangel.ru.git"
  BRANCH: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: |
          echo "PROJECT_PATH=${USER_PATH}/${DOMAIN}" >> $GITHUB_ENV
          echo "TEMP_PATH=${USER_PATH}/${DOMAIN}/temp" >> $GITHUB_ENV
          echo "CURRENT_PATH=${USER_PATH}/${DOMAIN}/current" >> $GITHUB_ENV

      - name: Deploy
        run: |
          sshpass -p "${PASSWORD}" ssh -o StrictHostKeyChecking=no "${USERNAME}@${HOST}" "bash -s" << EOF
          source ~/.nvm/nvm.sh
          PROJECT_PATH=${{env.PROJECT_PATH}}
          TEMP_PATH=${{env.TEMP_PATH}}
          CURRENT_PATH=${{env.CURRENT_PATH}}

          if [ ! -d "${PROJECT_PATH}" ]; then
            mkdir ${PROJECT_PATH}
            mkdir ${CURRENT_PATH}
            mkdir ${TEMP_PATH}
            cd ${TEMP_PATH}
            git clone -b ${BRANCH} ${REPO_URL} .

          else
            cd ${TEMP_PATH}
            git restore .
            git pull origin ${BRANCH}
          fi

          cd ${TEMP_PATH}
          yarn install
          yarn build

          rsync -rvaq --delete ${TEMP_PATH}/. ${CURRENT_PATH}

          if pm2 list | grep -q ${DOMAIN}; then
            cd ${CURRENT_PATH}
            pm2 restart ${DOMAIN}
          else
            cd ${CURRENT_PATH}
            pm2 start npm --name "${DOMAIN}" -- start
            pm2 save
          fi
          
          EOF
